version: '3'
services:
  database:
    image: flightoperatorreg.azurecr.io/postgres:latest
    container_name: database
    ports:
        - "5432"
    restart: always
  flightoperator:
    image: flightoperatorreg.azurecr.io/flightoperator:latest
    container_name: flightoperator
    ports:
        - "80:80"
        - "2112"
    restart: always
  prometheus:
    image: flightoperatorreg.azurecr.io/prometheus:latest
    container_name: prometheus
    ports:
        - "9090"
  grafana:
      image: flightoperatorreg.azurecr.io/grafana:latest
      container_name: grafana
      ports:
       - "3000:3000"
      depends_on:
        - prometheus