apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: flightoperatorreg.azurecr.io/postgres:latest
        ports:
        - containerPort: 5432
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 5432
  selector:
    app: database
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flightoperator
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: flightoperator
    spec:
      containers:
      - name: flightoperator
        image: flightoperatorreg.azurecr.io/flightoperator:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: flightoperator
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: flightoperator