{
 "title": "flightOperatorDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "/v1/flights GET Count",
   "type": "singlestat",
   "description": "counter of GET endpoint /v1/flights",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_get_all_counter" }
   ]
  },
  {
   "title": "/v1/flights POST Count",
   "type": "singlestat",
   "description": "counter of POST endpoint /v1/flights",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_create_flight_counter" }
   ]
  },
  {
   "title": "/v1/flights/<flightnumber> GET Count",
   "type": "singlestat",
   "description": "counter of GET endpoint /v1/flights/<flightnumber>",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_get_one_counter" }
   ]
  },
  {
   "title": "/v1/flights/<flightnumber> DELETE Count",
   "type": "singlestat",
   "description": "counter of POST endpoint /v1/flights",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_delete_counter" }
   ]
  },
  {
   "title": "PostgreSQL status",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "db_is_alive" }
   ]
  },
  {
   "title": "Saved flights",
   "type": "singlestat",
   "description": "Amount of saved flights in DB",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "app_flights_counter" }
   ]
  }
 ]
}